language: node_js
node_js:
  - "8"
  - "10"
  - "12"
deploy:
  on:
    tags: true
    branch: master
  provider: npm
  email: open-source-ops@aexp.com
  api_key:
    secure: CoI2EkAqBjTxphFuiKhCkXvzgnrIMFPKv5Qo8kiEpLrh8JtMkqQQH/FjXqeNF9zup8cBKZYGXza52YKOL61JLxMjaekNcRMs4eoIHj4ZrYPBjMajb931HoabLS2gg1cIC/ifoWNSMd6B+QasTtJWeMPrL6v5XBZF8QpBwcfd6nmmTukar1gkVLvkzHnIvxoERU+6t4aquNAFt6CFHtMx2A7Oi6QFv59c+noKu7pDi2WdxoAbPGLLiHExbU+5ILE0q2l5KgklTZCrRwz37EbeEe4XoGXVJVN3u/u2HRKl1lC53QI77578nfazZ7t14F9IBYoCoomQLbrjrrzj5UYX6XB0GGJw39v0MJ/rwgWBvCitZL8xmx02bLdK+eZo8euelCitiBo0wODmH54jFfJwjGBzKNGq+lJlcn1pUluJUEtJMiLZUJjmmU10QiNlEzZ8DBwYaWedHWi6zZ6EdHg3QafF2p0RAHlQC4PngQFy7vM3POLzftkIgHSpVx5+auxgXkWn8AVL0ZFYSZDfE7EiTThLgj2z35lGZMiYQXMGSaAwX0Qhv5D/f4Lt+33x/QU4cuMbnwCorgY4xURmOygkldkLDSEGoSvphD2LImh+ossYIg/GH8QXErxbq3wYcAmSPcPyFmwxH6W5KvXipZCcPcTW0m6PKAN59dwH2C7RKOQ=
